default:
	cat commandt.rst camelcasemotion.rst easymotion.rst lustyexplorer.rst  lustyjuggler.rst pydoc.rst | rst2pdf -o page1.pdf -s twocolumn
	rst2pdf tcomment.rst
	rst2pdf fugitive.rst
	rst2pdf verbal_emacs.rst -s twocolumn

all:
	cat *.rst | rst2pdf -o cheatsheet.pdf -s twocolumn
