default:
	cat commandt.rst camelcasemotion.rst easymotion.rst lustyexplorer.rst  lustyjuggler.rst | rst2pdf -o page1.pdf -s twocolumn
	rst2pdf tcomment.rst
	rst2pdf fugitive.rst

all:
	cat *.rst | rst2pdf -o cheatsheet.pdf -s twocolumn
